hw5
ipunicorn/Automatisation pull request #6
Opened 2022-09-07 20:12 UTC by ipunicorn

hw5

2022-09-11 14:39 UTC, konflic approved these changes

2022-09-11 14:39 UTC, konflic commented on example.py
> +from selenium import webdriver
А это что за файл и зачем он?

2022-09-11 14:39 UTC, konflic commented on conftest.py
> +        _browser = webdriver.Chrome()
А если у меня не настроены драйвера локально?

2022-09-12 08:39 UTC, ipunicorn commented on conftest.py
> +        _browser = webdriver.Chrome()
остается только страдать, получается
(исправлю)

2022-09-23 20:11 UTC, konflic requested changes

2022-09-23 20:11 UTC, konflic commented on conftest.py
> +        _browser = webdriver.Chrome()
Привет, пока не исправлено

2022-09-23 20:11 UTC, konflic commented on test_data/products.py
> +    return random.choice(_products)
В этом файле нет пустой строки в конце

2022-10-15 09:32 UTC, konflic approved these changes

2022-10-23 08:01 UTC, merged